### PR TITLE
Add new video streaming data doc, fix existing events doc

### LINKED ISSUE #757: Broadcast Streaming doc updates
Business case - Sync with the latest CN docs

Scope - Add a new doc [View Streaming Data.md](https://github.com/AgoraIO/Docs-Source/files/9877360/View.Streaming.Data.md) (maybe under the Develop section), and update https://github.com/AgoraIO/Docs-Source/blob/main/shared/broadcast-streaming/reference/_broadcast-streaming-events.mdx using the latest source file [Events.md](https://github.com/AgoraIO/Docs-Source/files/9877778/Events.md)

Additional information - Broadcast Streaming is not GA yet, but clients are already using it. Once the beta environment is ready on the new doc center, clients can see the latest docs right away.

Thanks in advance.

### PR DESCRIPTION
**Pull request by Kishan-Dhakan**
- Resolves #757

### CODE REVIEW

**Comment by billy-the-fish** [comment]
Some of the links are to the old docs so you need to clean up. Probably best to push this to the branch with Broadcast streaming in it, otherwise this will add these docs back to the build.

**Comment by billy-the-fish** [comment]
The branch that is keeping the broadcast streaming docs from: https://github.com/AgoraIO/Docs-Source/pull/811.

**Comment by billy-the-fish** [comment]
Ah, 
   For the broadcast streaming there need to be 2 branches. 

1. With Broadcast streaming removed that will be merged to main and published now. 
2. With Broadcast Streaming in it which will be published to main when Broadcast Streaming goes live. This change should be merged to that branch.

**Comment by Kishan-Dhakan** [comment]
Yep, so the branches accordingly are:
1. `remove-broadcast-docs`: It has removed broadcast docs and can be merged to staging/main.
2. `enhance-broadcast-streaming-kishan-staging`: Has the broadcast docs + enhancements from #757.
So 1 can be merged now and this PR can wait till broadcast goes live. Or I can also close this PR and re-open it later to reduce noise.

**Comment by billy-the-fish** [comment]
Or alternatively, we can merge this one to enhance-broadcast-streaming-kishan-staging and it will be ready to go when Broadcast Streaming goes live. If you could edit this PR and change the target branch, we could close this.

**Review by billy-the-fish — APPROVED** [review]
LGTM.

**Pull request merged**
