### PR TITLE
Add 'platform_selector: false' metadata to common docs

### LINKED ISSUE #1137: Add a metadata tag for all products that don't have different docs for each platform.
**Business case**: Helps improve the search

**Subject Matter Expert**: 
  - *Technical*: @Mr-spShuvo 
  - *Language*: @atovpeko 
  - *PM*: 

**Scope**: 
   - For all products that do not have different docs for each platform: (For example, Analytics)
       - For each root document in the product structure (as in, not the included docs, the ones in _develop_ etc.), add the following tag in the meta data at the had of the file: `platform_selector: false`
       - Please get this done for review by the 24/01/2023

**Acceptance criteria**: All docs have the correct metadata

**Additional valuable information**:

### PR DESCRIPTION
**Pull request by Kishan-Dhakan**
- Resolves #1137

### CODE REVIEW

**Comment by Kishan-Dhakan** [comment]
@Mr-spShuvo the other products have different docs for different platforms. Should I add this tag to all products regardless?

**Comment by Mr-spShuvo** [comment]
No. The original request was, add tags those top level pages, that doesn't have any platform selectors for example product overview page for all the products. Regardless the products, if a page doesn't have platform selector, add this front matter tag.

**Comment by Kishan-Dhakan** [comment]
@Mr-spShuvo I've updated the PR according to the requirements now

**Comment by Mr-spShuvo** [comment]
LGTM!

**Review by Mr-spShuvo — APPROVED** [review]
LGTM!

**Pull request merged**
