### PR TITLE
(WIP) Migrate broadcast streaming to mdx

### PR DESCRIPTION
**Pull request by dengyaxi**

### CODE REVIEW

**Comment by billy-the-fish** [comment]
Hi there, 
   Looks good. One thing, the REST API will be included in the API ref. @lemon-chen is adding the reference now. Can you please move the `restful-api` folder into `shared/broadcast-streaming` directory and update any l inks to point to the external API ref. Please use the <Link to="{{global.BROADCAST_STREAMING_API_REF_REST}}/FOLDER/FILENAME">LINKNAME</Link> linkage. (You will need to create the BROADCAST_STREAMING_API_REF_REST variable in globas.js ).
   We are going to publish the latest updated content today. Do you think this will take you a long time? If so, we can merge as is and make a ticket to update the API ref afterwards. Up to you.
   
      Cheers

     Iain

**Comment by dengyaxi** [comment]
@billy-the-fish Thanks for clarifying the API ref thing. We'll start working on it.

And because Broadcast streaming is not GA yet, we are not in a rush. Let's save this merge for later.

**Comment by billy-the-fish** [comment]
If we are not in a hurry, can you close this PR and reopen when we are ready to go GA please.

**Comment by dengyaxi** [comment]
Hi. The latest news is: Broadcast streaming goes GA together with the new site's hard release. The docset is still subject to change. I'll mark it as [WIP] for now in case of any confusion

**Comment by dengyaxi** [comment]
Merge for a branch cleanup

**Pull request merged**
